# Generated by Django 3.0.3 on 2020-04-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_createpoll_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpoll',
            old_name='opt_1',
            new_name='option_one',
        ),
        migrations.RenameField(
            model_name='createpoll',
            old_name='opt_1_count',
            new_name='option_one_count',
        ),
        migrations.RenameField(
            model_name='createpoll',
            old_name='opt_2',
            new_name='option_two',
        ),
        migrations.RenameField(
            model_name='createpoll',
            old_name='opt_2_count',
            new_name='option_two_count',
        ),
        migrations.RenameField(
            model_name='createpoll',
            old_name='questions',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='createpoll',
            name='opt_3_count',
        ),
    ]
